apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 139.59.6.252.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hackathon-ui-service
                port:
                  number: 80
